// <auto-generated />
using System.Collections.Generic;
using BarberAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberAPI.Models.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomeServiceActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShopServiceActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ShopAddress")
                        .HasColumnType("text");

                    b.Property<string>("ShopName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.BarberServiceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.ToTable("BarberServiceAreas");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<List<string>>("SavedAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.Barber", b =>
                {
                    b.HasOne("BarberAPI.Models.Concrete.AppUser", "AppUser")
                        .WithOne("BarberProfile")
                        .HasForeignKey("BarberAPI.Models.Concrete.Barber", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.BarberServiceArea", b =>
                {
                    b.HasOne("BarberAPI.Models.Concrete.Barber", "Barber")
                        .WithMany("ServiceAreas")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.Customer", b =>
                {
                    b.HasOne("BarberAPI.Models.Concrete.AppUser", "AppUser")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("BarberAPI.Models.Concrete.Customer", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.AppUser", b =>
                {
                    b.Navigation("BarberProfile")
                        .IsRequired();

                    b.Navigation("CustomerProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberAPI.Models.Concrete.Barber", b =>
                {
                    b.Navigation("ServiceAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
